version: "3.8"

services:

  ai:
    container_name: ai
    build:
      context: ../
      dockerfile: ./dockerFiles/AI/Dockerfile
    depends_on:
      - rabbitmq
    restart: always

  spring:
    container_name: spring
    build:
      context: ../
      dockerfile: ./dockerFiles/spring/Dockerfile
    depends_on:
      - db
      - rabbitmq
    volumes:
      - images:/images/
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
      
  db:
    volumes:       
      - postgres_data:/var/lib/postgresql/data
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
      
      
volumes: 
  postgres_data:
  images: